[supabase]
url = "https://kccdguiozegmdkveewkk.supabase.co" # L'URL de votre dashboard Supabase Cloud

api_key = "sb_publishable_MSQbCPW_RAKM9W8ratQlOg_8MBfK9Hk"

anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjY2RndWlvemVnbWRrdmVld2trIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY2NjMwMDYsImV4cCI6MjA4MjIzOTAwNn0.KyJypgOXEocYJd7IUxvG1C4tUCAMagKKh39-u_sUWqc"

service_role_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjY2RndWlvemVnbWRrdmVld2trIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NjY2MzAwNiwiZXhwIjoyMDgyMjM5MDA2fQ.9nrY8xtnomq-R0GBARW8ewLJek4xNJHxUz2E6MVvr-M"